import { User } from '../../domain/user.domain';
import {
  MOCK_PROFILE_ID_1,
  MOCK_PROFILE_ID_2,
  MOCK_PROFILE_ID_3,
  MOCK_PROFILE_ID_4,
  MOCK_PROFILE_ID_5,
} from './profiles.mock';

export const MOCK_USERS: User[] = [
  new User({
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_3,
  }),
  new User({
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_5,
  }),
  new User({
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice.johnson@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_1,
  }),
  new User({
    firstName: 'Bob',
    lastName: 'Brown',
    email: 'bob.brown@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_4,
  }),
  new User({
    firstName: 'Charlie',
    lastName: 'Davis',
    email: 'charlie.davis@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_2,
  }),
  new User({
    firstName: 'Diana',
    lastName: 'Evans',
    email: 'diana.evans@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_3,
  }),
  new User({
    firstName: 'Ethan',
    lastName: 'Foster',
    email: 'ethan.foster@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_4,
  }),
  new User({
    firstName: 'Fiona',
    lastName: 'Garcia',
    email: 'fiona.garcia@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_1,
  }),
  new User({
    firstName: 'George',
    lastName: 'Harris',
    email: 'george.harris@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_5,
  }),
  new User({
    firstName: 'Hannah',
    lastName: 'Irvine',
    email: 'hannah.irvine@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_2,
  }),
  new User({
    firstName: 'Ian',
    lastName: 'Jackson',
    email: 'ian.jackson@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_4,
  }),
  new User({
    firstName: 'Julia',
    lastName: 'King',
    email: 'julia.king@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_3,
  }),
  new User({
    firstName: 'Kevin',
    lastName: 'Lewis',
    email: 'kevin.lewis@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_5,
  }),
  new User({
    firstName: 'Laura',
    lastName: 'Morris',
    email: 'laura.morris@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_1,
  }),
  new User({
    firstName: 'Michael',
    lastName: 'Nelson',
    email: 'michael.nelson@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_2,
  }),
  new User({
    firstName: 'Nina',
    lastName: 'Owens',
    email: 'nina.owens@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_4,
  }),
  new User({
    firstName: 'Oscar',
    lastName: 'Perez',
    email: 'oscar.perez@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_3,
  }),
  new User({
    firstName: 'Paula',
    lastName: 'Quinn',
    email: 'paula.quinn@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_5,
  }),
  new User({
    firstName: 'Quentin',
    lastName: 'Roberts',
    email: 'quentin.roberts@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_1,
  }),
  new User({
    firstName: 'Rachel',
    lastName: 'Stewart',
    email: 'rachel.stewart@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_2,
  }),
  new User({
    firstName: 'Steven',
    lastName: 'Taylor',
    email: 'steven.taylor@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_4,
  }),
  new User({
    firstName: 'Tina',
    lastName: 'Upton',
    email: 'tina.upton@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_3,
  }),
  new User({
    firstName: 'Victor',
    lastName: 'Vargas',
    email: 'victor.vargas@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_5,
  }),
  new User({
    firstName: 'Wendy',
    lastName: 'White',
    email: 'wendy.white@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_1,
  }),
  new User({
    firstName: 'Xander',
    lastName: 'Young',
    email: 'xander.young@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_2,
  }),
  new User({
    firstName: 'Yvonne',
    lastName: 'Zimmerman',
    email: 'yvonne.zimmerman@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_4,
  }),
  new User({
    firstName: 'Zachary',
    lastName: 'Adams',
    email: 'zachary.adams@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_3,
  }),
  new User({
    firstName: 'Abigail',
    lastName: 'Baker',
    email: 'abigail.baker@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_5,
  }),
  new User({
    firstName: 'Benjamin',
    lastName: 'Carter',
    email: 'benjamin.carter@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_1,
  }),
  new User({
    firstName: 'Charlotte',
    lastName: 'Dixon',
    email: 'charlotte.dixon@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_2,
  }),
  new User({
    firstName: 'Daniel',
    lastName: 'Edwards',
    email: 'daniel.edwards@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_4,
  }),
  new User({
    firstName: 'Eleanor',
    lastName: 'Fisher',
    email: 'eleanor.fisher@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_3,
  }),
  new User({
    firstName: 'Frank',
    lastName: 'Gibson',
    email: 'frank.gibson@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_5,
  }),
  new User({
    firstName: 'Grace',
    lastName: 'Henderson',
    email: 'grace.henderson@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_1,
  }),
  new User({
    firstName: 'Henry',
    lastName: 'Ingram',
    email: 'henry.ingram@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_2,
  }),
  new User({
    firstName: 'Isla',
    lastName: 'Jones',
    email: 'isla.jones@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_4,
  }),
  new User({
    firstName: 'Jack',
    lastName: 'Kelly',
    email: 'jack.kelly@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_3,
  }),
  new User({
    firstName: 'Katherine',
    lastName: 'Lee',
    email: 'katherine.lee@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_5,
  }),
  new User({
    firstName: 'Liam',
    lastName: 'Martin',
    email: 'liam.martin@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_1,
  }),
  new User({
    firstName: 'Mia',
    lastName: 'Nelson',
    email: 'mia.nelson@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_2,
  }),
  new User({
    firstName: 'Nathan',
    lastName: 'Owens',
    email: 'nathan.owens@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_4,
  }),
  new User({
    firstName: 'Olivia',
    lastName: 'Parker',
    email: 'olivia.parker@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_3,
  }),
  new User({
    firstName: 'Patrick',
    lastName: 'Quinn',
    email: 'patrick.quinn@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_5,
  }),
  new User({
    firstName: 'Quinn',
    lastName: 'Reed',
    email: 'quinn.reed@example.com',
    isActive: false,
    profileId: MOCK_PROFILE_ID_1,
  }),
  new User({
    firstName: 'Rebecca',
    lastName: 'Scott',
    email: 'rebecca.scott@example.com',
    isActive: true,
    profileId: MOCK_PROFILE_ID_2,
  }),
];
